using Domain.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.FluentAPI
{
    public class FarmAcitvityConfigration : IEntityTypeConfiguration<FarmActivity>
    {
        public void Configure(EntityTypeBuilder<FarmActivity> builder)
        {
            // Tên bảng
            builder.ToTable("FarmActivities");

            // Khóa chính
            builder.HasKey(e => e.FarmActivitiesId);

            builder.Property(e => e.FarmActivitiesId)
                   .HasColumnName("farmActivitiesId")
                   .UseIdentityColumn(); // PostgreSQL: BIGINT GENERATED BY DEFAULT AS IDENTITY

            // Các cột đơn giản
            builder.Property(e => e.AssignedTo)
                   .HasColumnName("assignedTo");

            builder.Property(e => e.ActivityType)
                   .HasColumnName("activityType");

            builder.Property(e => e.StartDate)
                   .HasColumnName("startDate")
                   .HasColumnType("date");

            builder.Property(e => e.EndDate)
                   .HasColumnName("endDate")
                   .HasColumnType("date");

            builder.Property(e => e.Status)
                   .HasColumnName("status");

            builder.Property(e => e.CreatedAt)
                   .HasColumnName("createdAt");

            builder.Property(e => e.UpdatedAt)
                   .HasColumnName("updatedAt");

            builder.Property(e => e.createdBy)
                   .HasColumnName("createdBy");

            builder.Property(e => e.updatedBy)
                   .HasColumnName("updatedBy");

            builder.Property(e => e.scheduleId)
                   .HasColumnName("scheduleId");

            // Quan hệ với Schedule (1-n)
            builder.HasOne(e => e.Schedule)
                   .WithMany(s => s.FarmActivities)
                   .HasForeignKey(e => e.scheduleId)
                   .OnDelete(DeleteBehavior.Cascade);

            // Quan hệ với Account (AssignedTo)
            builder.HasMany(e => e.StaffFarmActivities)
                   .WithOne(a => a.FarmActivity)
                   .HasForeignKey(e => e.FarmActivityId)
                   .OnDelete(DeleteBehavior.Cascade);

        }

    }
}
