using Domain.Model;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.FluentAPI
{
    public class ScheduleConfigration : IEntityTypeConfiguration<Schedule>
    {
        public void Configure(EntityTypeBuilder<Schedule> builder)
        {
            // Tên bảng
            builder.ToTable("Schedules");

            // Khóa chính
            builder.HasKey(e => e.ScheduleId);

            builder.Property(e => e.ScheduleId)
                   .HasColumnName("scheduleId")
                   .UseIdentityColumn(); // BIGINT GENERATED BY DEFAULT AS IDENTITY

            // Các cột đơn giản
            builder.Property(e => e.ManagerId)
                   .HasColumnName("managerId");

            builder.Property(e => e.StartDate)
                   .HasColumnName("startDate")
                   .HasColumnType("date");

            builder.Property(e => e.EndDate)
                   .HasColumnName("endDate")
                   .HasColumnType("date");

            builder.Property(e => e.currentPlantStage)
                   .HasColumnName("currentPlantStage");

            builder.Property(e => e.toDay)
                   .HasColumnName("toDay")
                   .HasColumnType("date");

            builder.Property(e => e.Quantity)
                   .HasColumnName("quantity");

            builder.Property(e => e.Status)
                   .HasColumnName("status");

            builder.Property(e => e.PesticideUsed)
                   .HasColumnName("pesticideUsed");

            builder.Property(e => e.DiseaseStatus)
                   .HasColumnName("diseaseStatus");

            builder.Property(e => e.CreatedAt)
                   .HasColumnName("createdAt")
                   .HasColumnType("date");

            builder.Property(e => e.UpdatedAt)
                   .HasColumnName("updatedAt")
                   .HasColumnType("date");

            builder.Property(e => e.FarmId)
                   .HasColumnName("farmId");

            builder.Property(e => e.CropId)
                   .HasColumnName("cropId");

            // Quan hệ với Account (Manager/AssignedToNavigation)
            builder.HasOne(e => e.AssignedToNavigation)
                   .WithMany(a => a.Schedules) // giả định Account có ICollection<Schedule>
                   .HasForeignKey(e => e.ManagerId)
                   .OnDelete(DeleteBehavior.Cascade);

            // Quan hệ với Crop
            builder.HasOne(e => e.Crop)
                   .WithMany(c => c.Schedules) // giả định Crop có ICollection<Schedule>
                   .HasForeignKey(e => e.CropId)
                   .OnDelete(DeleteBehavior.Cascade);

            // Quan hệ với Farm
            builder.HasOne(e => e.FarmDetails)
                   .WithMany(f => f.Schedules) // giả định Farm có ICollection<Schedule>
                   .HasForeignKey(e => e.FarmId)
                   .OnDelete(DeleteBehavior.Cascade);

            // Quan hệ 1-n với FarmActivity
            builder.HasMany(e => e.FarmActivities)
                   .WithOne(fa => fa.Schedule)
                   .HasForeignKey(fa => fa.scheduleId)
                   .OnDelete(DeleteBehavior.Cascade);

            // Quan hệ 1-n với Inventory
            builder.HasMany(e => e.Inventories)
                   .WithOne(i => i.Schedule)
                   .HasForeignKey(i => i.ScheduleId)
                   .OnDelete(DeleteBehavior.Cascade);

            // Quan hệ 1-n với ScheduleLog
            builder.HasMany(e => e.ScheduleLog)
                   .WithOne(sl => sl.schedule)
                   .HasForeignKey(sl => sl.ScheduleId)
                   .OnDelete(DeleteBehavior.Cascade);


        }
    }
}


